name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: Run on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Build
        run: |
          pnpm install
          pnpm build
          pnpm bundle
      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: pnpm lint
      - name: Test
        if: matrix.os == 'windows-latest'
        run: |
          pnpm test
      - name: Test & Coverage
        if: matrix.os == 'ubuntu-latest'
        run: |
          pnpm test-cov
          pnpm check-format
          pnpm merge-report && cat coverage/lcov.info
      - name: Upload Coveralls Report
        if: success() && matrix.os == 'ubuntu-latest'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
